### ISSUE TITLE
최초 지갑 중복 생성

### ISSUE THREAD

**Issue by firepunch** [boxfox619/Linkbit-Application#44]
'이더링'이라는 지갑을 최초에 생성하였는데 중복되어 만들어집니다.
![img_0672](https://user-images.githubusercontent.com/16695705/52520891-55fdad80-2cb2-11e9-8ac9-681f0394c492.PNG)

**Comment by boxfox619** [comment]
지갑 생성시 생성 버튼을 빠르게 두번 클릭하면 해당 현상 발생.
디바운스 처리, progress dialog 적용으로 해결함
